"""empty message

Revision ID: 2ac3554d52a9
Revises: 
Create Date: 2019-08-07 00:01:38.973469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac3554d52a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('authors', sa.String(length=100), nullable=True),
    sa.Column('publishedDate', sa.DateTime(), nullable=True),
    sa.Column('industryIdentifiers', sa.String(length=500), nullable=True),
    sa.Column('pageCount', sa.Integer(), nullable=True),
    sa.Column('imageLinks', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
