"""empty message

Revision ID: 892cafafe93a
Revises: 
Create Date: 2019-08-11 20:22:03.405808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892cafafe93a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=5000), nullable=True),
    sa.Column('authors', sa.String(length=100), nullable=True),
    sa.Column('publishedDate', sa.DateTime(), nullable=True),
    sa.Column('industryIdentifiers', sa.String(length=5000), nullable=True),
    sa.Column('pageCount', sa.Integer(), nullable=True),
    sa.Column('imageLinks', sa.String(length=5000), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
